defaultPlatforms:
- linux/arm64
- linux/amd64
builds:
- id: cloudflare-tunnel-ingress-controller
  dir: ./
  main: ./cmd/cloudflare-tunnel-ingress-controller/
  ldflags:
  - '{{ if index .Env "LD_FLAGS" }}{{ .Env.LD_FLAGS }}{{ end }}'