apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: cloudflare-tunnel-ingress-controller
build:
  artifacts:
    - image: cloudflare-tunnel-ingress-controller
      docker:
        dockerfile: image/cloudflare-tunnel-ingress-controller/Dockerfile
        noCache: false
        pullParent: false
        squash: false
  local:
    useBuildkit: true
manifests:
  rawYaml:
    - hack/dev/ns.yaml
    - hack/dev/cloudflare-api.yaml
    - hack/dev/deployment.yaml
