apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-tunnel-ingress-controller.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: controller
    {{- include "cloudflare-tunnel-ingress-controller.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.metrics.serviceMonitor.create }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    {{- end }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "cloudflare-tunnel-ingress-controller.selectorLabels" . | nindent 4 }}
