apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudflare-tunnel-ingress-controller.fullname" . }}-controlled-cloudflared-connector
  labels:
    {{- include "cloudflare-tunnel-ingress-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudflare-tunnel-ingress-controller.fullname" . }}-controlled-cloudflared-connector
subjects:
  - name: {{ include "cloudflare-tunnel-ingress-controller.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}