{{- if not (hasKey .Values.cloudflare "secretRef") }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api
stringData:
  api-token: "{{ .Values.cloudflare.apiToken }}"
  cloudflare-account-id: "{{ .Values.cloudflare.accountId }}"
  cloudflare-tunnel-name: "{{ .Values.cloudflare.tunnelName }}"
{{- end }}
