{{- if not $.Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel-ingress-controller.fullname" $ }}
stringData:
  api-token: "{{ .Values.cloudflare.apiToken }}"
  cloudflare-account-id: "{{ .Values.cloudflare.accountId }}"
  cloudflare-tunnel-name: "{{ .Values.cloudflare.tunnelName }}"
{{- end }}
