name: Helm Package Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
      - name: Run helm package
        run: |
          helm package ./helm/cloudflare-tunnel-ingress-controller
