name: Helm Package Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
      - name: Run helm package
        run: |
          helm package ./helm/cloudflare-tunnel-ingress-controller
