name: Integration Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: './go.mod'
      - name: Run integration tests
        run: |
          make integration-test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac
        with:
          files: ./test/integration/cover.out
          flags: integration
          token: ${{ secrets.CODECOV_TOKEN }}
