name: Latest Docker Image

on:
  workflow_dispatch: {}
  push:
    tags:
    - v*

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: "Extract Version"
      id: extract_version
      run: |
        GIT_TAG=${GITHUB_REF##*/}
        VERSION=${GIT_TAG##v}
        echo "::set-output name=version::$(echo $VERSION)"
    - uses: actions/checkout@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: make image
    - name: Push docker image to ghcr.io
      env:
        VERSION: ${{ steps.extract_version.outputs.version }}
      run: | 
        docker tag ghcr.io/strrl/cloudflare-tunnel-ingress-controller:latest ghcr.io/strrl/cloudflare-tunnel-ingress-controller:$VERSION
        docker push ghcr.io/strrl/cloudflare-tunnel-ingress-controller:$VERSION
